### ISSUE TITLE
proposal: unpublish sysninja.vscode-ansible-mod extension from marketplace

### ISSUE THREAD

**Issue by FlorianLaunay** [nklmilojevic/nklmilojevic#1]
Hi @nklmilojevic. In order to avoid avoid confusing Ansible users looking for vscode extensions, could you be so kind to un publish this extension from the marketplace? Now there is an actively maintained community extension that includes the autocompletion, errors debugging and vaulting features : https://marketplace.visualstudio.com/items?itemName=zbr.vscode-ansible

Note: there is no need to "delete" extension from marketplace, using "unpublish" is enough in order to hide extension from normal searches, an action that is also reversible (as opposed to delete) : https://code.visualstudio.com/api/working-with-extensions/publishing-extension#unpublishing-extensions

I suppose the likely url to perform this from for you would be https://marketplace.visualstudio.com/manage/publishers/sysninja

**Comment by nklmilojevic** [comment]
Hey @FlorianLaunay thanks for bringing this to my attention, I completely forgot that I forked it for my own needs quite a while ago. 

I just deleted the extension - shouldn't show up anymore.

**Comment by FlorianLaunay** [comment]
Many thanks :pray:
